### ISSUE TITLE
No Module Named Constance

### ISSUE THREAD

**Issue by abec427** [sflems/led-board-manager#28]
Super Noob here...

I have the NHL, MLB, and NFL boards all working. The NHL board is running with supervisor, and the other two I am just using SSH through Terminal. I would love to use this manager to switch boards.  When I try to start the server, I get the error "No module Named Constance".  I did the automatic install.  I would love help to get pointed in the right direction to troubleshoot. This is what I get:  

(env) pi@Rileypi:~/led-board-manager $ source env/bin/activate && gunicorn Capstone.wsgi -b 0:9002
[2022-11-16 02:48:32 -0500] [1665] [INFO] Starting gunicorn 20.0.4
[2022-11-16 02:48:32 -0500] [1665] [INFO] Listening at: http://0.0.0.0:9002 (1665)
[2022-11-16 02:48:32 -0500] [1665] [INFO] Using worker: sync
[2022-11-16 02:48:32 -0500] [1666] [INFO] Booting worker with pid: 1666
[2022-11-16 02:48:34 -0500] [1666] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/led-board-manager/env/lib/python3.9/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/led-board-manager/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/led-board-manager/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/led-board-manager/env/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/led-board-manager/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/led-board-manager/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/led-board-manager/env/lib/python3.9/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/pi/led-board-manager/Capstone/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/pi/led-board-manager/env/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/pi/led-board-manager/env/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/pi/led-board-manager/env/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/pi/led-board-manager/env/lib/python3.9/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/pi/led-board-manager/scoreboard/apps.py", line 2, in <module>
    from constance.apps import ConstanceConfig
ModuleNotFoundError: No module named 'constance'
[2022-11-16 02:48:34 -0500] [1666] [INFO] Worker exiting (pid: 1666)
[2022-11-16 02:48:35 -0500] [1665] [INFO] Shutting down: Master
[2022-11-16 02:48:35 -0500] [1665] [INFO] Reason: Worker failed to boot.
(env) pi@Rileypi:~/led-board-manager $

**Comment by sflems** [comment]
Sorry for the delay, I can look into this sometime in the next few days. 

Did the install script happen to throw any errors? It looks as if one of the dependencies isn't installed, (or initiated correctly on my end).

If you follow the manual step to install the pip requirements, it may very well say if there was an issue at that point.

**Comment by abec427** [comment]
Thanks, 

It did not throw errors with the auto install until I got the error above.  I tried the manual install, and after entering pip3 install -r requirements.txt is gave me these errors:

> WARNING: Discarding git+https://github.com/sflems/django-constance.git@master#egg=django-constance. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Collecting aiohttp==3.7.4
  Using cached https://www.piwheels.org/simple/aiohttp/aiohttp-3.7.4-cp39-cp39-linux_armv7l.whl (1.3 MB)
Requirement already satisfied: asgiref==3.3.1 in ./env/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (3.3.1)
Requirement already satisfied: async-timeout==3.0.1 in ./env/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (3.0.1)
Requirement already satisfied: attrs==20.3.0 in ./env/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (20.3.0)
Requirement already satisfied: beautifulsoup4==4.9.3 in ./env/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (4.9.3)
Requirement already satisfied: certifi==2020.12.5 in ./env/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (2020.12.5)
Requirement already satisfied: colorzero==1.1 in ./env/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (1.1)
Requirement already satisfied: Django==3.1.3 in ./env/lib/python3.9/site-packages (from -r requirements.txt (line 8)) (3.1.3)
Collecting django-bootstrap4==2.3.1
  Using cached https://www.piwheels.org/simple/django-bootstrap4/django_bootstrap4-2.3.1-py3-none-any.whl (24 kB)
ERROR: Could not find a version that satisfies the requirement django-constance (unavailable)
ERROR: No matching distribution found for django-constance (unavailable)

**Comment by sflems** [comment]
Alright! Managed to tackle the issue regarding a missing requirement. Give the following a rip from the `led-board-manager` directory and you should be rolling:

```
source env/bin/activate
python -m pip install -r requirements
```

It looks like the rest of the setup went well for you so this should solve the issue. Otherwise just let me know and I can reopen this. Cheers!
